### ISSUE TITLE
Not found

### ISSUE THREAD

**Issue by eteache** [SergiX44/oddcast-tts-php#1]
Hola,

Primero, gracias por la librería, tiene muy buena pinta.
Lo segundo, cuando la intento utilizar copiando los ejemplos del README, después de instalarla e importarla correctamente con Composer, recibo el siguiente error:

`PHP Fatal error:  Uncaught Error: Class 'SergiX44\OddcastTTS\Oddcast' not found`

He probado algunas cosas pero no he conseguido solucionarlo. Las demás librerías que tengo instaladas funcionan perfectamente.

Thanks!

**Comment by sergix44** [comment]
Have you loaded the composer autoload beforey?

**Comment by eteache** [comment]
Hi,
Yes, the code is very simply. 

![image](https://user-images.githubusercontent.com/1094037/99044865-bc52e680-2590-11eb-8ece-de0e7453320e.png)

I even checked if autoload.php exist with file_exists, and returns true.

**Comment by sergix44** [comment]
It seems a strange issue with psr-0 autoload, it doesn't create the classmap, I'll look into it.

**Comment by eteache** [comment]
I see some differences with the composer.json from Github and the one downloaded automatically (setted to version "^1.0") from composer update. Maybe that is the problem.
![image](https://user-images.githubusercontent.com/1094037/99088330-33f23700-25cc-11eb-80c2-e96b2d5a0601.png)

**Comment by sergix44** [comment]
You where right, the composer.json was different from packagist, I don't know why.
Try to update to 1.1, that should works.

**Comment by eteache** [comment]
Now works perfectly!
